"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PhoneCall, Clock, CalendarCheck, BarChart3 } from "lucide-react";

interface VoiceAnalyticsProps {
  agentId: string;
}

export function VoiceAnalytics({ agentId }: VoiceAnalyticsProps) {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium">Voice Analytics</h3>
        <p className="text-sm text-muted-foreground">
          Performance metrics for this AI agent's voice calls.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Calls</CardTitle>
            <PhoneCall className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">--</div>
            <p className="text-xs text-muted-foreground">
              Awaiting data
            </p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Average Duration</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">--:--</div>
            <p className="text-xs text-muted-foreground">
              Awaiting data
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Minutes Used</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">-- / 100</div>
            <p className="text-xs text-muted-foreground">
              Current billing cycle
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Appointments</CardTitle>
            <CalendarCheck className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">--</div>
            <p className="text-xs text-muted-foreground">
              Generated by voice
            </p>
          </CardContent>
        </Card>
      </div>
      
      <Card className="flex flex-col items-center justify-center p-12 text-center border-dashed">
        <div className="rounded-full bg-slate-100 p-3 mb-4">
          <BarChart3 className="h-8 w-8 text-slate-400" />
        </div>
        <h3 className="text-lg font-semibold mb-2">Detailed Call Analytics Coming Soon</h3>
        <p className="text-muted-foreground max-w-sm text-sm">
          Call logs, recordings, transcripts, and detailed performance metrics will appear here after the system is fully active.
        </p>
      </Card>
    </div>
  );
}
