export const KNOWLEDGE_BASE_SEED_DATA = [
  // Buying
  {
    question: "What is the first step in the home buying process?",
    answer: "The first step is getting pre-approved for a mortgage. This helps you understand how much you can afford and shows sellers you are a serious buyer.",
    category: "Buying",
    tags: ["first-time buyer", "process", "mortgage"],
    searchKeywords: "start, beginning, first step, pre-approval, loan",
    displayOrder: 10,
  },
  {
    question: "How much do I need for a down payment?",
    answer: "While 20% is traditionally recommended to avoid Private Mortgage Insurance (PMI), many programs allow down payments as low as 3% to 5% for first-time buyers, and VA or USDA loans may require 0% down.",
    category: "Buying",
    tags: ["down payment", "finance", "mortgage"],
    searchKeywords: "how much, money, downpayment, percentage, PMI",
    displayOrder: 20,
  },
  {
    question: "What is earnest money?",
    answer: "Earnest money is a 'good faith' deposit made when submitting an offer. It typically ranges from 1% to 3% of the purchase price and is held in escrow until closing, where it is applied to your down payment or closing costs.",
    category: "Buying",
    tags: ["deposit", "offer", "escrow"],
    searchKeywords: "earnest, deposit, good faith, offer",
    displayOrder: 30,
  },
  {
    question: "Should I get a home inspection?",
    answer: "Yes, a home inspection is highly recommended. It reveals hidden issues with the property's structure, systems, and appliances before you finalize the purchase, potentially saving you thousands in unexpected repairs.",
    category: "Buying",
    tags: ["inspection", "due diligence"],
    searchKeywords: "inspect, inspector, hidden issues, repairs",
    displayOrder: 40,
  },
  {
    question: "How long does it take to buy a house?",
    answer: "On average, finding a home takes 4-10 weeks, and the closing process takes another 30-45 days after the offer is accepted.",
    category: "Buying",
    tags: ["timeline", "process"],
    searchKeywords: "how long, time, average duration, closing time",
    displayOrder: 50,
  },
  // Selling
  {
    question: "When is the best time to sell my house?",
    answer: "Spring and early summer are traditionally the best times to sell due to favorable weather and families wanting to move before the new school year. However, local market conditions can influence this.",
    category: "Selling",
    tags: ["timing", "market"],
    searchKeywords: "best time, season, spring, summer",
    displayOrder: 10,
  },
  {
    question: "How do you determine the listing price?",
    answer: "We perform a Comparative Market Analysis (CMA), looking at recently sold, active, and pending properties in your neighborhood that are similar in size, condition, and features to price your home competitively.",
    category: "Selling",
    tags: ["pricing", "cma", "valuation"],
    searchKeywords: "price, value, worth, CMA, comps",
    displayOrder: 20,
  },
  {
    question: "What should I do to prepare my house for sale?",
    answer: "Declutter, depersonalize, deep clean, and handle minor repairs. Curb appeal is also crucial, so ensure the exterior is well-maintained. We can also discuss staging options.",
    category: "Selling",
    tags: ["preparation", "staging"],
    searchKeywords: "prep, prepare, fix, clean, stage",
    displayOrder: 30,
  },
  {
    question: "Do I need to stage my home?",
    answer: "While not strictly required, staged homes typically sell faster and for a higher price. It helps buyers visualize themselves living in the space.",
    category: "Selling",
    tags: ["staging", "preparation"],
    searchKeywords: "stage, staging, furniture, interior",
    displayOrder: 40,
  },
  {
    question: "What are closing costs for a seller?",
    answer: "Seller closing costs typically range from 6% to 10% of the sale price. This includes agent commissions, title insurance, transfer taxes, and prorated property taxes.",
    category: "Selling",
    tags: ["fees", "closing"],
    searchKeywords: "closing costs, fees, seller fees, commission",
    displayOrder: 50,
  },
  // Renting
  {
    question: "What do I need to apply for a rental?",
    answer: "Typically, you need a completed application, proof of income (pay stubs or tax returns), a valid ID, and consent for a background and credit check.",
    category: "Renting",
    tags: ["application", "requirements"],
    searchKeywords: "apply, application, requirements, documents",
    displayOrder: 10,
  },
  {
    question: "What is a standard security deposit?",
    answer: "A standard security deposit is usually equivalent to one month's rent, though this can vary based on your credit score, pets, and local laws.",
    category: "Renting",
    tags: ["deposit", "money"],
    searchKeywords: "deposit, security deposit, move-in cost",
    displayOrder: 20,
  },
  {
    question: "Are pets allowed in the rental?",
    answer: "Pet policies vary by property. Some allow pets with restrictions on breed and weight, often requiring an additional pet deposit or monthly pet rent, while others strictly prohibit them.",
    category: "Renting",
    tags: ["pets", "policies"],
    searchKeywords: "pets, dog, cat, animal, pet deposit",
    displayOrder: 30,
  },
  {
    question: "Who is responsible for maintenance?",
    answer: "Landlords handle major repairs (plumbing, HVAC, appliances), while tenants are usually responsible for minor upkeep like changing light bulbs, air filters, and maintaining cleanliness.",
    category: "Renting",
    tags: ["maintenance", "responsibilities"],
    searchKeywords: "fix, repair, broken, maintenance, landlord",
    displayOrder: 40,
  },
  // Commercial
  {
    question: "What is a Triple Net (NNN) Lease?",
    answer: "In a Triple Net lease, the tenant pays the base rent plus their share of the property's taxes, insurance, and common area maintenance (CAM) expenses.",
    category: "Commercial",
    tags: ["lease terms", "NNN"],
    searchKeywords: "triple net, NNN, lease, CAM, commercial lease",
    displayOrder: 10,
  },
  {
    question: "How is commercial rent calculated?",
    answer: "Commercial rent is typically calculated on a price per square foot basis annually. For example, 1,000 sq ft at $20/sq ft equals $20,000 per year, or $1,666 per month.",
    category: "Commercial",
    tags: ["rent calculation", "pricing"],
    searchKeywords: "calculate rent, square foot, commercial price",
    displayOrder: 20,
  },
  {
    question: "What is a Letter of Intent (LOI)?",
    answer: "An LOI is a non-binding proposal outlining the basic terms of a lease or purchase agreement before drafting the formal contract.",
    category: "Commercial",
    tags: ["documents", "LOI"],
    searchKeywords: "LOI, letter of intent, proposal, terms",
    displayOrder: 30,
  },
  {
    question: "What does 'Vanilla Shell' mean?",
    answer: "A vanilla shell refers to a commercial space that is partially finished, usually including a finished ceiling, walls ready for painting, electrical outlets, and a working restroom.",
    category: "Commercial",
    tags: ["condition", "build-out"],
    searchKeywords: "vanilla shell, white box, build out, condition",
    displayOrder: 40,
  },
  // Investment
  {
    question: "What is the 1% rule in real estate investing?",
    answer: "The 1% rule is a rule of thumb stating that the monthly rent of an investment property should be at least 1% of the total purchase price to ensure positive cash flow.",
    category: "Investment",
    tags: ["ROI", "strategy"],
    searchKeywords: "1% rule, one percent rule, return, cash flow",
    displayOrder: 10,
  },
  {
    question: "What is a Cap Rate?",
    answer: "The Capitalization Rate (Cap Rate) measures the expected annual rate of return on a property. It is calculated by dividing the Net Operating Income (NOI) by the property's current market value.",
    category: "Investment",
    tags: ["metrics", "ROI"],
    searchKeywords: "cap rate, capitalization rate, ROI, return on investment",
    displayOrder: 20,
  },
  {
    question: "What is a 1031 Exchange?",
    answer: "A 1031 exchange allows investors to defer paying capital gains taxes on an investment property if the proceeds are reinvested into a 'like-kind' property within specific timeframes.",
    category: "Investment",
    tags: ["tax", "exchange"],
    searchKeywords: "1031, tax deferred, exchange, capital gains",
    displayOrder: 30,
  },
  {
    question: "What is 'House Hacking'?",
    answer: "House hacking involves buying a multi-unit property (like a duplex or triplex), living in one unit, and renting out the others so the tenants' rent covers the mortgage.",
    category: "Investment",
    tags: ["strategy", "multifamily"],
    searchKeywords: "house hacking, house hack, duplex, rent out",
    displayOrder: 40,
  },
  // Financing
  {
    question: "What is the difference between pre-qualification and pre-approval?",
    answer: "Pre-qualification is an estimate of what you can borrow based on unverified information. Pre-approval is a firm commitment from a lender after verifying your financial documents and credit history.",
    category: "Financing",
    tags: ["mortgage", "approval"],
    searchKeywords: "pre-qualify, pre-approve, pre-approval, difference",
    displayOrder: 10,
  },
  {
    question: "What is Private Mortgage Insurance (PMI)?",
    answer: "PMI is an insurance policy protecting the lender if you default on your loan. It is usually required if your down payment is less than 20% of the home's purchase price.",
    category: "Financing",
    tags: ["insurance", "fees"],
    searchKeywords: "PMI, private mortgage insurance, down payment, under 20",
    displayOrder: 20,
  },
  {
    question: "Fixed-rate vs. Adjustable-rate mortgage (ARM)?",
    answer: "A fixed-rate mortgage keeps the same interest rate for the life of the loan. An ARM typically has a lower initial rate that adjusts periodically based on market indexes after an initial fixed period.",
    category: "Financing",
    tags: ["loan types", "interest"],
    searchKeywords: "fixed, ARM, adjustable, interest rate, rates",
    displayOrder: 30,
  },
  // Legal
  {
    question: "What does Title Insurance cover?",
    answer: "Title insurance protects you and the lender from financial loss due to defects in a property's title, such as unknown liens, encumbrances, or past ownership disputes.",
    category: "Legal",
    tags: ["title", "insurance"],
    searchKeywords: "title insurance, title, deed, liens",
    displayOrder: 10,
  },
  {
    question: "What is an easement?",
    answer: "An easement grants someone else the legal right to use a portion of your property for a specific purpose, such as a utility company accessing power lines or a neighbor sharing a driveway.",
    category: "Legal",
    tags: ["property rights", "easement"],
    searchKeywords: "easement, rights, neighbor, utility line",
    displayOrder: 20,
  },
  {
    question: "What are CC&Rs?",
    answer: "Covenants, Conditions, and Restrictions (CC&Rs) are rules established by a Homeowners Association (HOA) or builder that dictate how you can use, alter, or maintain your property.",
    category: "Legal",
    tags: ["HOA", "rules"],
    searchKeywords: "CC&R, HOA rules, restrictions, covenants",
    displayOrder: 30,
  },
  // Documentation
  {
    question: "What is a Seller's Property Disclosure?",
    answer: "This is a legally required document where the seller outlines any known defects, issues, or past repairs made to the property before the buyer signs a contract.",
    category: "Documentation",
    tags: ["disclosure", "forms"],
    searchKeywords: "disclosure, seller disclosure, defects, forms",
    displayOrder: 10,
  },
  {
    question: "What is a HUD-1 or Closing Disclosure?",
    answer: "The Closing Disclosure is a five-page form providing final details about the mortgage loan you have selected. It includes the loan terms, your projected monthly payments, and how much you will pay in fees.",
    category: "Documentation",
    tags: ["closing", "forms"],
    searchKeywords: "HUD, Closing Disclosure, settlement statement, final numbers",
    displayOrder: 20,
  },
  // Pricing
  {
    question: "Will pricing my home higher give me room to negotiate?",
    answer: "Overpricing your home often deters potential buyers and leads to the property sitting on the market. It is generally better to price it at market value to attract serious offers quickly.",
    category: "Pricing",
    tags: ["strategy", "negotiation"],
    searchKeywords: "overprice, room to negotiate, high price",
    displayOrder: 10,
  },
  {
    question: "How do upgrades affect my home's value?",
    answer: "Not all upgrades offer a 100% return on investment. Kitchen and bathroom remodels generally yield the best return, while highly personalized upgrades (like a swimming pool) may not add equivalent value.",
    category: "Pricing",
    tags: ["value", "upgrades"],
    searchKeywords: "upgrades, remodel, ROI, value, improvements",
    displayOrder: 20,
  },
  // Property Viewing
  {
    question: "What are 'Open House' best practices?",
    answer: "Ensure the home is spotless, secure valuables and medications, turn on all lights, open blinds for natural light, and leave the property so buyers feel comfortable discussing it openly.",
    category: "Property Viewing",
    tags: ["open house", "showing"],
    searchKeywords: "open house, showing, prep, prepare",
    displayOrder: 10,
  },
  {
    question: "Should I attend the showing of my own house?",
    answer: "No, it is highly recommended that sellers leave during showings. Buyers feel more comfortable exploring and speaking freely without the current owner present.",
    category: "Property Viewing",
    tags: ["showing", "etiquette"],
    searchKeywords: "attend showing, stay home, leave house",
    displayOrder: 20,
  },
  // General
  {
    question: "What is a dual agency?",
    answer: "Dual agency occurs when a real estate agent represents both the buyer and the seller in the same transaction. This must be fully disclosed to both parties as it can create a conflict of interest.",
    category: "General",
    tags: ["agency", "representation"],
    searchKeywords: "dual agency, represent both, same agent",
    displayOrder: 10,
  },
  {
    question: "What does 'Under Contract' mean?",
    answer: "Under contract means the seller has accepted an offer from a buyer, but the transaction hasn't closed yet because contingencies (like inspections or financing) still need to be met.",
    category: "General",
    tags: ["status", "contract"],
    searchKeywords: "under contract, pending, accepted offer",
    displayOrder: 20,
  },
  {
    question: "What is an appraisal?",
    answer: "An appraisal is an unbiased professional estimation of a home's value, required by lenders to ensure the property is worth the amount of the loan they are providing.",
    category: "General",
    tags: ["valuation", "lending"],
    searchKeywords: "appraisal, appraiser, value, lender requirement",
    displayOrder: 30,
  },
  {
    question: "What is a contingency?",
    answer: "A contingency is a condition that must be met before a real estate contract becomes legally binding, such as the buyer securing financing or the home passing an inspection.",
    category: "General",
    tags: ["contract", "conditions"],
    searchKeywords: "contingency, condition, back out, protection",
    displayOrder: 40,
  },
  {
    question: "What happens on Closing Day?",
    answer: "On closing day, you'll sign the final paperwork, pay any remaining closing costs, the title will officially transfer, and the buyer receives the keys to the property.",
    category: "General",
    tags: ["closing", "timeline"],
    searchKeywords: "closing day, final day, get keys, sign papers",
    displayOrder: 50,
  },
  {
    question: "Do I need a real estate agent?",
    answer: "While you can buy or sell on your own (FSBO), a licensed agent provides market expertise, negotiation skills, contract management, and access to a broader network, significantly reducing stress and legal risks.",
    category: "General",
    tags: ["agent", "representation"],
    searchKeywords: "need agent, FSBO, for sale by owner, why use agent",
    displayOrder: 60,
  },
  {
    question: "What is a Homeowners Association (HOA)?",
    answer: "An HOA is an organization in a subdivision or planned community that makes and enforces rules for the properties and their residents, usually requiring monthly or annual fees.",
    category: "General",
    tags: ["HOA", "community"],
    searchKeywords: "HOA, homeowners association, fees, rules",
    displayOrder: 70,
  },
  {
    question: "What is an escrow account?",
    answer: "An escrow account is held by a neutral third party during the transaction to hold funds and documents. After closing, lenders often use an escrow account to hold a portion of your monthly payment to pay property taxes and insurance on your behalf.",
    category: "General",
    tags: ["escrow", "finance"],
    searchKeywords: "escrow, account, third party, hold money",
    displayOrder: 80,
  }
];
